### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by bhaveshchavda53** [ankitrathore25/RateMyPhone#6]
showing internal error after clicking the searches button.(Is there  an error  in connecting to dataset??)

**Comment by ankitrathore25** [comment]
I don't think there is any such error. Dataset is csv file so there is no such connection issue. It is even working [here](http://dm4.pythonanywhere.com/). Please show me what error you are getting?

**Comment by bhaveshchavda53** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/33779319/69691160-34ac6780-10f4-11ea-837b-4902b33afd4d.png)
showing this error after clicking search
![Screenshot (23)](https://user-images.githubusercontent.com/33779319/69691848-3414d080-10f6-11ea-83c0-a69a9beca09a.png)

**Comment by ankitrathore25** [comment]
just go to the terminal tab, there you will be able to see the errors.

**Comment by bhaveshchavda53** [comment]
![Screenshot (24)](https://user-images.githubusercontent.com/33779319/69733954-2f7f0500-1154-11ea-8f07-cdf1b4423096.png)
No result and no error shown in terminal



Are all the mentioned requirement(in requirement folder) needed to run successfully

**Comment by ankitrathore25** [comment]
it is not a problem of requirements. If a requirement is missing then there would be error. In your case, their is high chance that preprocess() method is not being called. If you know how to debug then check preprocess method must be called otherwise there will not be any output. Just read the readme to understand why preprocessing is important.
